import { Application } from "./types";

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: "1",
    company: { id: "c1", name: "Stripe", industry: "Fintech", size: "1000-5000", website: "stripe.com" },
    role: "Senior Software Engineer",
    status: "technical",
    appliedDate: "2026-05-12",
    salary: { min: 180000, max: 220000, currency: "USD" },
    location: "San Francisco, CA",
    remote: true,
    priority: "high",
    lastActivity: "2026-05-28",
    notes: "Recruiter reached out via LinkedIn. Strong team match.",
    jobUrl: "https://stripe.com/jobs",
    stages: [
      { id: "s1", name: "Recruiter Call", date: "2026-05-15", notes: "30 min with Sarah. Very positive.", completed: true, type: "phone" },
      { id: "s2", name: "Technical Screen", date: "2026-05-22", notes: "LeetCode-style. Two medium problems.", completed: true, type: "technical" },
      { id: "s3", name: "System Design", date: "2026-06-04", notes: "Design a payment gateway.", completed: false, type: "technical" },
    ],
  },
  {
    id: "2",
    company: { id: "c2", name: "Linear", industry: "Developer Tools", size: "50-200", website: "linear.app" },
    role: "Staff Engineer",
    status: "onsite",
    appliedDate: "2026-05-08",
    salary: { min: 200000, max: 250000, currency: "USD" },
    location: "Remote",
    remote: true,
    priority: "high",
    lastActivity: "2026-05-30",
    notes: "Applied directly. Big fan of their product philosophy.",
    stages: [
      { id: "s4", name: "Intro Call", date: "2026-05-13", notes: "Met with CTO Tuomas.", completed: true, type: "phone" },
      { id: "s5", name: "Technical Interview", date: "2026-05-20", notes: "Deep dive into TypeScript architecture.", completed: true, type: "technical" },
      { id: "s6", name: "On-site Loop", date: "2026-06-05", notes: "4 rounds across product, eng, design.", completed: false, type: "onsite" },
    ],
  },
  {
    id: "3",
    company: { id: "c3", name: "Vercel", industry: "Developer Tools", size: "200-500", website: "vercel.com" },
    role: "Principal Engineer",
    status: "offer",
    appliedDate: "2026-04-20",
    salary: { min: 220000, max: 280000, currency: "USD" },
    location: "Remote",
    remote: true,
    priority: "high",
    lastActivity: "2026-05-29",
    notes: "Offer received 5/29. Deadline 6/6.",
    stages: [
      { id: "s7", name: "Phone Screen", date: "2026-04-25", notes: "HR intro call.", completed: true, type: "phone" },
      { id: "s8", name: "Technical", date: "2026-05-05", notes: "Next.js architecture discussion.", completed: true, type: "technical" },
      { id: "s9", name: "On-site", date: "2026-05-16", notes: "5 rounds, all went well.", completed: true, type: "onsite" },
      { id: "s10", name: "Offer Call", date: "2026-05-29", notes: "$250k base + equity.", completed: true, type: "other" },
    ],
  },
  {
    id: "4",
    company: { id: "c4", name: "Figma", industry: "Design Tools", size: "500-1000", website: "figma.com" },
    role: "Engineering Manager",
    status: "phone_screen",
    appliedDate: "2026-05-20",
    salary: { min: 200000, max: 240000, currency: "USD" },
    location: "San Francisco, CA",
    remote: false,
    priority: "medium",
    lastActivity: "2026-05-27",
    notes: "Interesting EM role. Would require relocation.",
    stages: [
      { id: "s11", name: "HR Screen", date: "2026-05-27", notes: "30 min culture fit.", completed: true, type: "phone" },
      { id: "s12", name: "Hiring Manager Call", date: "2026-06-06", notes: "Scheduled for next Friday.", completed: false, type: "phone" },
    ],
  },
  {
    id: "5",
    company: { id: "c5", name: "Notion", industry: "Productivity", size: "200-500", website: "notion.so" },
    role: "Senior Frontend Engineer",
    status: "applied",
    appliedDate: "2026-05-25",
    salary: { min: 160000, max: 195000, currency: "USD" },
    location: "New York, NY",
    remote: true,
    priority: "medium",
    lastActivity: "2026-05-25",
    notes: "Applied through careers page. Referral from Alex.",
    stages: [],
  },
  {
    id: "6",
    company: { id: "c6", name: "Datadog", industry: "DevOps", size: "5000+", website: "datadoghq.com" },
    role: "Senior Software Engineer",
    status: "rejected",
    appliedDate: "2026-04-10",
    salary: { min: 155000, max: 190000, currency: "USD" },
    location: "New York, NY",
    remote: false,
    priority: "low",
    lastActivity: "2026-05-01",
    notes: "Rejected after system design round. Feedback: scope too narrow.",
    stages: [
      { id: "s13", name: "Recruiter Call", date: "2026-04-14", notes: "Standard intro.", completed: true, type: "phone" },
      { id: "s14", name: "System Design", date: "2026-04-24", notes: "Went okay but not great.", completed: true, type: "technical" },
    ],
  },
  {
    id: "7",
    company: { id: "c7", name: "PlanetScale", industry: "Database", size: "50-200", website: "planetscale.com" },
    role: "Senior Infrastructure Engineer",
    status: "wishlist",
    appliedDate: "",
    location: "Remote",
    remote: true,
    priority: "medium",
    lastActivity: "2026-05-30",
    notes: "Interesting MySQL-based scaling role. Haven't applied yet.",
    stages: [],
  },
  {
    id: "8",
    company: { id: "c8", name: "Anthropic", industry: "AI/ML", size: "200-500", website: "anthropic.com" },
    role: "Software Engineer, Infra",
    status: "applied",
    appliedDate: "2026-05-28",
    salary: { min: 200000, max: 280000, currency: "USD" },
    location: "San Francisco, CA",
    remote: true,
    priority: "high",
    lastActivity: "2026-05-28",
    notes: "Dream company. Applied to infra team.",
    stages: [],
  },
];
